repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        name: ESLint for ECR Viewer
        files: ^containers/ecr-viewer/.*\.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx in containers/ecr-viewer
        types: [file]
        additional_dependencies:
          - eslint@8.56.0
          - eslint-config-next
          - eslint-config-prettier
          - "@typescript-eslint/parser"
          - "@typescript-eslint/eslint-plugin"
          - typescript
          - "@next/eslint-plugin-next"
          - eslint-plugin-unused-imports
          - eslint-plugin-jsdoc
        args: ["--config=./containers/ecr-viewer/.eslintrc.json", "--fix"]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks
  autofix_prs: true
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: monthly
  skip: []
  submodules: false
exclude: |
  (?x)^(
    examples/.*|
    containers/ecr-viewer/seed-scripts/baseECR/.*|
    containers/message-parser/schema/.*.htm
  )$
